blank_issues_enabled: false
contact_links:
  - name: "Alert! Are you sure you're talking to the right people?"
    url: https://github.com/gooberscan/CobbleGuard/issues
    about: "We warn servers about griefing. If a spam bot impersonated us, please be cautious."
